# app.yaml: The main configuration file for your Arduino App.
# This file describes the application's metadata and properties.

# The user-visible name of the application.
name: LeRobot Policy Deployment App

# A brief description of what the application does.
description: "Deploy a behaviour-cloned NumPy MLP robot-control policy to the Arduino UNO Q and drive servos in real time while monitoring actions live through the web interface."

# The icon for the application, can be an emoji or a short string.
icon: 🤖

# A list of network ports that the application exposes.
# Example: [80, 443]
ports: [7000]

# A list of bricks used by this application.
bricks:
  - arduino:web_ui
